/**
 * demo 组件演示页面
 */

Page({
    data: {
        list:[
            {
                name:"guanbi-fill"
            },
            {
                name:"fangda"
            },
            {
                name:"aixin"
            },
            {
                name:"daxingxing"
            },
            {
                name:"fangdajing"
            },
            {
                name:"dianzanshu"
            },
            {
                name:"jiantou"
            },
            {
                name:"pinpaiguan"
            },
            {
                name:"huo"
            },
            {
                name:"gonggao"
            },
            {
                name:"xiaoxingxing"
            },
            {
                name:"wode"
            },
            {
                name:"zhongxingxing"
            },
            {
                name:"shouye"
            },
            {
                name:"xihuan"
            },
            {
                name:"jia"
            },
            {
                name:"jian"
            },
            {
                name:"close"
            },
            {
                name:"pz"
            },
            {
                name:"error"
            },
            {
                name:"success"
            },
            {
                name:"share"
            },
            {
                name:"not-list"
            },
            {
                name:"member"
            },
            {
                name:"location"
            },
            {
                name:"tel"
            },
            {
                name:"cartquan"
            },
            {
                name:"canico"
            },
            {
                name:"cartjian"
            },
            {
                name:"site"
            },
            {
                name:"dpindex"
            },
            {
                name:"dpcart"
            },
            {
                name:"dpshare"
            },
            {
                name:"shouyefenxiang"
            },
            {
                name:"guanbianniu"
            },
            {
                name:"indexcartminus"
            },
            {
                name:"indexcartadd"
            },
            {
                name:"copy"
            }
        ]
    },
    click() {

    }
});
